### ISSUE TITLE
Update heroku deployment

### ISSUE THREAD

**Issue by Apercu** [thibaudgg/circleci-badges#2]
Hi,

I just saw that you've not updated your heroku application with the latest changes, could you do it? I just love clean badges :)

I've cloned and hosted myself your project but it would be great if yours was up-to-date too.

Bye!

**Comment by thibaudgg** [comment]
Hey @Apercu, could you fire a quick PR? Thanks!

**Comment by Apercu** [comment]
No need for a PR, you just have to update the heroku remote :)

**Comment by thibaudgg** [comment]
@Apercu actually I should delete this repo as you can now directly ask CirceCI for nice badges with: `?style=shield&circle-token=XXX`
Thanks for the issue.

**Comment by Apercu** [comment]
Well I don't like their shield badge, too much shadow and I prefer the sober `build passing` message, I'm difficult I know.
You should not delete your repo, that's a good project :)

**Comment by thibaudgg** [comment]
Heroku deployment updated, thanks!
